@startuml Example
interface CondicionIVA {
  impuesto(monto)
}

class ConsumidorFinal implements CondicionIVA {
  impuesto(monto)
}

class ResponsableInscripto implements CondicionIVA {
  impuesto(monto)
}

class ResponsableNoInscripto implements CondicionIVA {
  impuesto(monto)
}

class Cliente {
  saldo
  comprar(producto)
}

Cliente --> "1" CondicionIVA
Cliente ..> Producto 

class Producto {
  precio()
}

class ProductoEspecial extends Producto {
  precio()
}
@enduml
